= Abstract

Modern organizations operate in an increasingly complex and volatile cybersecurity landscape, in which new vulnerabilities are disclosed daily, infrastructures evolve constantly and adversaries continuously adapt their tactics. Attack graphs are a well established formalism for modelling multi step adversarial behaviour and reasoning about feasible attack paths within a networked system. However, each attack graph execution produces a static, snapshot based model that reflects the facts available at that point in time. MulVAL's existing mechanisms can refresh vulnerability repository data and process scanner output, but input refresh alone does not determine whether a change affects the graph structure or integrate threat modeling facts into attack graph generation. As a result, there remains a significant gap between threat intelligence processing and automated attack graph generation.

This dissertation proposes a dynamic framework that systematically links continuously evolving threat intelligence with the generation and maintenance of attack graphs. The framework complements MulVAL's existing data integration capabilities by correlating intelligence with an asset inventory expressed through CPEs, enabling analysis where vulnerability scans cannot be performed or are inappropriate, and by integrating structured threat modeling facts. It integrates both quantitative metrics and qualitative intelligence, gathered through an automated Open-Source Intelligence (OSINT) acquisition and normalization pipeline, and relies on the MulVAL logical reasoning engine to derive attack paths from system configurations, vulnerabilities and adversarial assumptions. Mechanisms for selective regeneration and contextual reprioritization determine whether changed facts require a new graph or whether only path priorities must be recalculated. Visualization and analytical components transform the resulting models into actionable insights. The proposed approach is evaluated through case study scenarios that examine its functional behavior, dynamic update mechanisms and effectiveness in supporting proactive cyber defense. Overall, the framework extends individual snapshot based attack graph analyses with an intelligence informed maintenance workflow for cybersecurity management.

*Keywords* #h(10pt) attack graphs, threat intelligence, MulVAL, OSINT, risk assessment, cybersecurity

#pagebreak()

= Resumo

As organizações modernas operam num cenário de cibersegurança cada vez mais complexo e volátil, no qual são divulgadas novas vulnerabilidades diariamente, as infraestruturas evoluem constantemente e os adversários adaptam continuamente as suas táticas. Os grafos de ataque constituem um formalismo bem estabelecido para modelar o comportamento adversarial em múltiplas etapas e para raciocinar sobre os caminhos de ataque viáveis num sistema em rede. Contudo, cada execução de um grafo de ataque produz um modelo estático e pontual, que reflete os factos disponíveis nesse momento. Os mecanismos existentes do MulVAL podem atualizar dados de repositórios de vulnerabilidades e processar resultados de scans, mas a atualização dos dados não determina por si só se uma alteração afeta a estrutura do grafo nem integra factos de threat modeling na geração do grafo de ataque. Como consequência, persiste uma lacuna significativa entre o processamento de threat intelligence e a geração automática de grafos de ataque.

Esta dissertação propõe uma plataforma dinâmica que liga de forma sistemática a threat intelligence em constante evolução à geração e manutenção de grafos de ataque. A plataforma complementa as capacidades existentes de integração de dados do MulVAL ao correlacionar inteligência com um inventário de ativos expresso através de CPEs, permitindo analisar ativos para os quais os scans de vulnerabilidades não podem ser efetuados ou não são adequados, e ao integrar factos estruturados de threat modeling. Integra tanto métricas quantitativas como inteligência qualitativa, recolhidas através de uma cadeia automatizada de aquisição e normalização de inteligência de fontes abertas (OSINT), e recorre ao motor de raciocínio lógico MulVAL para derivar caminhos de ataque a partir das configurações do sistema, das vulnerabilidades e dos pressupostos adversariais. Mecanismos de regeneração seletiva e repriorização contextual determinam se factos alterados exigem um novo grafo ou se apenas devem ser recalculadas as prioridades dos caminhos. Os componentes de visualização e análise transformam os modelos resultantes em conhecimento acionável. A abordagem proposta é avaliada através de casos de estudo que examinam o seu comportamento funcional, os seus mecanismos de atualização dinâmica e a sua eficácia no apoio a uma ciberdefesa proativa. Em síntese, a plataforma complementa análises pontuais de grafos de ataque com um processo de manutenção informado por inteligência para a gestão da cibersegurança.

*Palavras-chave* #h(10pt) grafos de ataque, threat intelligence, MulVAL, OSINT, avaliação de risco, cibersegurança
