= Abstract

Modern organizations face a volatile cybersecurity landscape in which vulnerabilities are disclosed daily, infrastructures evolve and adversaries adapt their tactics. Attack graphs model adversarial behavior across multiple stages and feasible attack paths in networked systems. Each graph is derived from the configuration, vulnerability and adversarial facts available for a given environment, and therefore represents its state at that time. Input refresh alone does not establish whether changes are relevant to the modeled environment or alter the graph structure. Threat modeling facts are also not systematically integrated into attack graph generation. Consequently, the integration of evolving threat intelligence and threat modeling into attack graph generation remains insufficiently addressed.

This dissertation proposes a dynamic framework that systematically integrates both continuously evolving threat intelligence and threat modeling into the generation and maintenance of attack graphs. It correlates threat intelligence with CPE based asset inventories to analyze assets that cannot or should not be scanned, and translates structured threat modeling outputs into attack graph facts. An automated open source intelligence (OSINT) pipeline collects and normalizes quantitative metrics and qualitative intelligence, combining them with system configurations, vulnerabilities and adversarial assumptions to derive attack paths with MulVAL. Mechanisms for selective regeneration and contextual reprioritization determine whether changed facts require a new graph or only the recalculation of path priorities. Graphs annotated with risk information and host level summaries support exposure identification and prioritization. The approach is evaluated through case studies that examine functional behavior, dynamic updates and effectiveness in proactive cyber defense. Overall, the framework extends point in time attack graph analyses with an intelligence informed maintenance workflow.

*Keywords* #h(10pt) attack graphs, threat intelligence, MulVAL, OSINT, risk assessment, cybersecurity

#pagebreak()

= Resumo

As organizações modernas enfrentam um cenário de cibersegurança volátil, no qual são divulgadas vulnerabilidades diariamente, as infraestruturas evoluem e os adversários adaptam as suas táticas. Os grafos de ataque modelam o comportamento adversarial em múltiplas etapas e permitem analisar caminhos de ataque viáveis em sistemas em rede. Cada grafo é derivado dos factos relativos a configurações, vulnerabilidades e pressupostos adversariais disponíveis para um determinado ambiente e representa, por isso, o seu estado nesse momento. A atualização isolada dos dados de entrada não determina se as alterações são relevantes para o ambiente modelado ou modificam a estrutura do grafo. Os factos de threat modeling também não são integrados de forma sistemática na geração de grafos de ataque. Consequentemente, a integração de threat intelligence em evolução e de threat modeling na geração de grafos de ataque permanece insuficientemente tratada.

Esta dissertação propõe uma plataforma dinâmica que integra sistematicamente tanto a threat intelligence em constante evolução como o threat modeling na geração e manutenção de grafos de ataque. Correlaciona a threat intelligence com inventários de ativos baseados em CPEs para analisar ativos que não podem ou não devem ser submetidos a scans e traduz resultados estruturados de threat modeling em factos para a geração de grafos de ataque. Uma cadeia automatizada de inteligência de fontes abertas (OSINT) recolhe e normaliza métricas quantitativas e inteligência qualitativa, combinando-as com configurações do sistema, vulnerabilidades e pressupostos adversariais para derivar caminhos de ataque com o MulVAL. Mecanismos de regeneração seletiva e repriorização contextual determinam se factos alterados exigem um novo grafo ou apenas o recálculo das prioridades dos caminhos. Grafos anotados com informação de risco e resumos ao nível dos hosts apoiam a identificação e priorização de exposições. A abordagem é avaliada em casos de estudo que examinam o comportamento funcional, as atualizações dinâmicas e a eficácia no apoio a uma ciberdefesa proativa. Em síntese, a plataforma complementa análises pontuais de grafos de ataque com um processo de manutenção informado por inteligência.

*Palavras-chave* #h(10pt) grafos de ataque, threat intelligence, MulVAL, OSINT, avaliação de risco, cibersegurança
